# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 585f76303c21463b4eea03d0786a2c23d43b154e1919bf26dbcd107340da8e85f21dda28c36b22d455c90c2548e1d4ed59be7c00a0060024dfcdc194d7f38ac1

test:
  secret_key_base: ef215500381551d40b782ba45775af776a7fcb2a945144811de67421a4c993df5f063c24427a94babd2ce832de3b0821a0f3e956e4d3afc4b3ce000d8d639991

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
